# Generated by Django 5.1.4 on 2025-02-15 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_delete_storeusersimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
