# Generated by Django 5.1.4 on 2025-01-19 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0002_databaseclothes_size_g_databaseclothes_size_gg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseclothes',
            name='price',
            field=models.FloatField(verbose_name=[django.core.validators.MinValueValidator('10'), django.core.validators.MaxValueValidator('380')]),
        ),
    ]
