# Generated by Django 5.1.4 on 2025-01-19 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0003_alter_databaseclothes_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseclothes',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator('10'), django.core.validators.MaxValueValidator('380')]),
        ),
    ]
