# Generated by Django 5.1.4 on 2025-01-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0005_alter_databaseclothes_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseclothes',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
