# Generated by Django 5.1.4 on 2025-01-27 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0006_databaseclothes_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseclothes',
            name='size_g',
        ),
        migrations.RemoveField(
            model_name='databaseclothes',
            name='size_gg',
        ),
        migrations.RemoveField(
            model_name='databaseclothes',
            name='size_m',
        ),
        migrations.RemoveField(
            model_name='databaseclothes',
            name='size_p',
        ),
        migrations.RemoveField(
            model_name='databaseclothes',
            name='size_pp',
        ),
        migrations.AddField(
            model_name='databaseclothes',
            name='cross_databases',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='databaseclothes',
            name='test',
            field=models.BooleanField(choices=[('Size GG', 'gg'), ('Size G', 'g'), ('Size M', 'm'), ('Size P', 'p'), ('Size PP', 'pp')], default=False),
        ),
    ]
