# Generated by Django 5.1.4 on 2025-01-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0007_remove_databaseclothes_size_g_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseclothes',
            name='test',
        ),
        migrations.AddField(
            model_name='databaseclothes',
            name='size_g',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databaseclothes',
            name='size_gg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databaseclothes',
            name='size_m',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databaseclothes',
            name='size_p',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databaseclothes',
            name='size_pp',
            field=models.BooleanField(default=False),
        ),
    ]
