# Generated by Django 5.1.4 on 2025-01-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0008_remove_databaseclothes_test_databaseclothes_size_g_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseclothes',
            name='size_g',
        ),
        migrations.RemoveField(
            model_name='databaseclothes',
            name='size_gg',
        ),
        migrations.RemoveField(
            model_name='databaseclothes',
            name='size_m',
        ),
        migrations.RemoveField(
            model_name='databaseclothes',
            name='size_p',
        ),
        migrations.RemoveField(
            model_name='databaseclothes',
            name='size_pp',
        ),
    ]
