# Generated by Django 5.1.4 on 2025-01-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0009_remove_databaseclothes_size_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseclothes',
            name='size_GG',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databaseclothes',
            name='size_PP',
            field=models.BooleanField(default=False),
        ),
    ]
