# Generated by Django 5.1.4 on 2025-01-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0010_databaseclothes_size_gg_databaseclothes_size_pp'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseclothes',
            name='size_G',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databaseclothes',
            name='size_M',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databaseclothes',
            name='size_P',
            field=models.BooleanField(default=False),
        ),
    ]
