# Generated by Django 5.1.4 on 2025-02-06 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0011_databaseclothes_size_g_databaseclothes_size_m_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseclothes',
            name='cross_databases',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Clothes_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
