# Generated by Django 5.1.4 on 2025-03-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0012_alter_databaseclothes_cross_databases'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseclothes',
            name='description',
            field=models.TextField(default='simple description'),
            preserve_default=False,
        ),
    ]
