# Generated by Django 5.1.7 on 2025-04-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0013_databaseclothes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseclothes',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
