# Generated by Django 5.1.4 on 2025-05-17 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0014_databaseclothes_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Api_Clothes.databaseclothes')),
            ],
        ),
    ]
