# Generated by Django 5.1.4 on 2025-05-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0017_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseclothes',
            name='category',
            field=models.ManyToManyField(related_name='clothes', to='Api_Clothes.category'),
        ),
    ]
