# Generated by Django 5.1.4 on 2025-05-18 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0018_databaseclothes_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='hex_code',
            new_name='hex',
        ),
    ]
