# Generated by Django 5.1.4 on 2025-05-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0019_rename_hex_code_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
