# Generated by Django 5.1.4 on 2025-05-21 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0020_size_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='amount',
        ),
        migrations.CreateModel(
            name='ClothesSizeColorStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_stocks', to='Api_Clothes.databaseclothes')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api_Clothes.size')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
        ),
    ]
