# Generated by Django 5.1.4 on 2025-05-22 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0021_remove_size_amount_clothessizecolorstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothessizecolorstock',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api_Clothes.color'),
            preserve_default=False,
        ),
    ]
