# Generated by Django 5.1.4 on 2025-05-22 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_Clothes', '0022_clothessizecolorstock_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clothessizecolorstock',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='databaseclothes',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='databaseclothes',
            name='sizes',
        ),
        migrations.AlterField(
            model_name='clothessizecolorstock',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_stock', to='Api_Clothes.color'),
        ),
        migrations.AlterField(
            model_name='clothessizecolorstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='Api_Clothes.databaseclothes'),
        ),
        migrations.AlterField(
            model_name='clothessizecolorstock',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_stock', to='Api_Clothes.size'),
        ),
    ]
